### ISSUE TITLE
Bounded law violation?

### ISSUE THREAD

**Issue by hdgarrood** [rgrempel/purescript-int-53#8]
Of course, many numeric types only 'mostly' follow laws, and I think this is understandable. But perhaps it's worth noting somewhere in the documentation that it's possible to get an `Int53` which is greater than `top`?

For example:
```purescript
module Main where

import Prelude
import Data.Int53 as Int53
import Control.Monad.Eff.Console (log)

main =
  when (top + two > top :: Int53.Int53) (log "Bounded law violated")
  where
  two = one + one
```

Somewhat related, I was browsing the source and noticed [this comment](https://github.com/rgrempel/purescript-int-53/blob/23db9134112ed78f8b97557d0941e6a57a3f2e14/src/Data/Int53.purs#L146-L148):

> Purescript is more aggressive than this with the `Int` type,
> dropping fractional parts via `(i | 0)` even when you wouldn't
> think a fractional part was possible.

The reason the `Int` type does that even when fractional parts are not possible (eg `add` and `mul`) is to ensure that the result is in the 32-bit range, so that `top` and `bottom` really are upper and lower bounds (unless you cheat with the FFI / `unsafeCoerce`), and also so that when it does under/overflow, the behaviour is at least generally understood and (relatively) easy to predict, just in case that wasn't clear.

**Comment by rgrempel** [comment]
Ah, interesting, I had not thought of that.

I suppose that my design goal is to mirror the behaviour of `Int` as much as possible, just with wider bounds. So, I would be tempted to implement something that does actually enforce `top` and `bottom`. Though, I suppose the performance implications are probably worse than they are for `Int`, since `(i | 0)` is probably pretty efficient, and what I'd have to do here is probably less efficient.

In any event, I'll give it a try and benchmark it -- perhaps it won't be too bad, performance-wise.
